/**
 * @file Centralized constants used across the astro-media package.
 * @description Keeping defaults here prevents magic numbers/strings, ensures consistency,
 * and makes configuration easier to manage.
 */

/**
 * Default responsive image widths used by <SmartImage> when no `widths` prop is provided.
 * These values cover a standard range of device breakpoints from mobile to large desktops.
 * The widths are sorted in ascending order.
 * @type {number[]}
 */
export const DEFAULT_RESPONSIVE_WIDTHS: number[] = [640, 750, 828, 1080, 1200, 1920, 2560];

/**
 * Default image formats preference order for the <Picture> component in <SmartImage>.
 * Astro will generate images in these formats and the browser will pick the first one it supports.
 * 'avif' is preferred for its superior compression, with 'webp' as a widely supported fallback.
 * @type {('avif' | 'webp')[]}
 */
export const DEFAULT_IMAGE_FORMATS: ("avif" | "webp")[] = ["avif", "webp"];

/**
 * Default quality setting for images generated by Astro's asset pipeline.
 * This value is passed to the underlying Sharp image processor.
 * `80` is generally considered a good balance between file size and visual fidelity.
 * @type {number}
 */
export const DEFAULT_IMAGE_QUALITY: number = 80;

/**
 * A map of common aspect ratios to their corresponding TailwindCSS padding-bottom percentages.
 * This is useful for creating aspect-ratio boxes for video or image containers.
 * The padding-bottom trick maintains the aspect ratio of a container with a height of 0.
 *
 * @example
 * ```astro
 * <div class={`relative h-0 ${ASPECT_RATIO_PADDING['16:9']}`}>
 *   <iframe class="absolute top-0 left-0 w-full h-full" />
 * </div>
 * ```
 *
 * @type {Record<'16:9' | '4:3' | '1:1', string>}
 */
export const ASPECT_RATIO_PADDING: Record<"16:9" | "4:3" | "1:1", string> = {
  "16:9": "pb-[56.25%]", // (9 / 16) * 100
  "4:3": "pb-[75%]", // (3 / 4) * 100
  "1:1": "pb-[100%]", // (1 / 1) * 100
};

/**
 * Default fallback for the `duration` property in the SEO JSON-LD schema for videos.
 * Represents a duration of 0 minutes and 0 seconds in ISO 8601 format.
 * Used in <SmartVideo> when no `metadata.duration` is provided.
 * @type {string}
 */
export const DEFAULT_DURATION_ISO: string = "PT0M0S";
